TOOL_CONVERT = {"gardentool":"Garden Tools", 
               "seedpouch":"Seed Pouch",
               "tree":"Tree of Lights",
               "gardengloves":"Garden Gloves",
               "cleaningtool":"Cleaning Tools",
               "tools":"Tools",
               "flower":"Yellow Lily",
               "anemone":"Anemone",
               "butterfly":"Butterfly",
               "bench":"Bench",
               "sketchtool":"Designing Tools",
               "tile":"Tile",
               "fond":"Pond",
               "brick":"Brick",
               "lemonbag":"Lemon Bag",
               "paint":"Paints",
               "vase":"Vase",
               "light":"Light",
               "statue":"Statue",
               "screws":"Nails",
               "birds":"Bird Statue",
               "logs":"Logs",
               "cleansers":"Cleansers",
               "xp":"Experience Points (XP)",
               "eventcoin":"EventCoin",
               "stonebasket":"Stone Basket",
               "terrarium":"Terrarium"} 

REWARD_CONVERT = {"birdcage":"Golden Cage",
                 "bluechest":"Granma's Chest",
                 "brownchest":"Mystery Box",
                 "cleaningtoolbox":"Cleaning Tool Box",
                 "cleaningpack":"Old Cleaning Box",
                 "flowerpot":"Flowerpot",
                 "tree":"Tree of Lights",
                 "gardeningpack":"Old Gardening Tool Box",
                 "gardentool":"Garden Tools",
                 "gold":"Coins",
                 "seedpack":"Old Seed Box",
                 "sketchpack":"Old Design Tool Box",
                 "toolpack":"Old Tool Box",
                 "xp":"Experience Points (XP)",
                 "goldchest":"Gold Pocket",
                 "jewel":"Jewels",
                 "magictimer":"Magic Timer",
                 "sketchtoolbox":"Workbench",
                 "timeskip":"Hourglass"}