TOOL_CONVERT = {"gardentool":"Garden Tools", 
               "seedpouch":"Seed Pouch",
               "tree":"Tree of Lights",
               "gardengloves":"Garden Gloves",
               "cleaningtool":"Cleaning Tools",
               "tools":"Tools",
               "flower":"Yellow Lily",
               "anemone":"Anemone",
               "butterfly":"Butterfly",
               "bench":"Bench",
               "sketchtool":"Designing Tools",
               "tile":"Tile",
               "fond":"Pond",
               "brick":"Brick",
               "lemonbag":"Lemon Bag",
               "paint":"Paints",
               "vase":"Vase",
               "light":"Light",
               "statue":"Statue",
               "screws":"Nails",
               "birds":"Bird Statue",
               "logs":"Logs",
               "cleansers":"Cleansers",
               "xp":"Experience Points (XP)",
               "eventcoin":"EventCoin",
               "stonebasket":"Stone Basket",
               "terrarium":"Terrarium"} 

REWARD_CONVERT = {"birdcage":"Golden Cage",
                 "bluechest":"Granma's Chest",
                 "brownchest":"Mystery Box",
                 "cleaningtoolbox":"Cleaning Tool Box",
                 "cleaningpack":"Old Cleaning Box",
                 "flowerpot":"Flowerpot",
                 "tree":"Tree of Lights",
                 "gardeningpack":"Old Gardening Tool Box",
                 "gardentool":"Garden Tools",
                 "gold":"Coins",
                 "seedpack":"Old Seed Box",
                 "sketchpack":"Old Design Tool Box",
                 "toolpack":"Old Tool Box",
                 "xp":"Experience Points (XP)",
                 "goldchest":"Gold Pocket",
                 "jewel":"Jewels",
                 "magictimer":"Magic Timer",
                 "sketchtoolbox":"Workbench",
                 "timeskip":"Hourglass"}

CHAR_CONVERT = {"catpepper": "Pepper",
                "catginger": "Ginger",
                "catace": "Ace"}

HARD_ITEMS = {'bench_06', 
              'bench_07', 
              'bench_08', 
              'birds_01', 
              'birds_06', 
              'birds_07', 
              'birds_08', 
              'birds_09', 
              'birds_10', 
              'butterfly_04', 
              'butterfly_05', 
              'butterfly_06', 
              'cleaningtool_10', 
              'cleaningtool_12', 
              'cleansers_06', 
              'cleansers_07', 
              'eventcoin', 
              'gardentool_10', 
              'gardentool_11', 
              'gardentool_12', 
              'gardentool_13', 
              'gardentool_14', 
              'gardentool_15', 
              'lemonbag_01', 
              'lemonbag_02', 
              'lemonbag_03', 
              'lemonbag_04', 
              'lemonbag_06', 
              'lemonbag_07', 
              'screws_04', 
              'screws_05', 
              'sketchtool_10', 
              'sketchtool_11', 
              'sketchtool_12', 
              'sketchtool_13', 
              'sketchtool_14', 
              'sketchtool_15', 
              'statue_08', 
              'statue_09', 
              'statue_11', 
              'statue_12', 
              'statue_13', 
              'stonebasket_05', 
              'tools_09', 
              'tools_10', 
              'tools_11', 
              'tree_05', 
              'tree_06', 
              'tree_07', 
              'tree_08', 
              'vase_06', 
              'vase_07'}